steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cremona', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cremona']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cremona'
      - '--image=gcr.io/$PROJECT_ID/cremona'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--timeout=3600'
      - '--session-affinity'
      - '--set-env-vars=API_KEY=${_API_KEY},OPEN_ROUTER_API_KEY=${_OPEN_ROUTER_API_KEY}'

substitutions:
  _API_KEY: ''
  _OPEN_ROUTER_API_KEY: ''
